package:
  name: libyaml
  version: 0.2.5

source:
  sha256: c642ae9b75fee120b2d96c712538bd2cf283228d2337df2cf2988e3c02678ef4 
  url: https://github.com/yaml/libyaml/releases/download/0.2.5/yaml-0.2.5.tar.gz

build:
  library: true
  script: |
     CFLAGS="-fPIC" emconfigure ./configure
     emmake make install -j ${PYODIDE_JOBS:-3}
